# Generated by Django 4.1.4 on 2023-05-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vechileapp', '0003_vehicle_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='img',
            new_name='image',
        ),
    ]
